Fix regression in #include directive paths
BoschSensortec/BSEC-Arduino-library pull request #58
Opened 2023-01-30 18:23 UTC by per1234

These `#include` directives were modified to expect the target files in the same folder as the containing file (https://github.com/boschsensortec/BSEC-Arduino-library/commit/f772ae1125f56d4495406e848dedd9642af3bb14), but those files are not in that folder. This caused compilation of any sketch using the library to fail:

```cpp
#include <bsec.h>
void setup() {}
void loop() {}
```

```text
c:\Users\per\Documents\Arduino\libraries\BSEC_Software_Library\src/bsec.h:46:10: fatal error: bsec_datatypes.h: No such file or directory #include "bsec_datatypes.h"
^~~~~~~~~~~~~~~~~~
```

The target files are in the `inc` subfolder, so that relative path must be specified in the `#include` directive as before.

2023-01-30 21:38 UTC, cyberman54 commented
I can confirm this issue:

```
In file included from .pio/libdeps/usb/BSEC Software Library/src/bsec.cpp:39:
.pio/libdeps/usb/BSEC Software Library/src/bsec.h:46:10: fatal error: bsec_datatypes.h: No such file or directory
```

Bosch: Didn't you test this release?

2023-01-31 20:15 UTC, limerickcabin reviewed
on line 48, I had to use #include "bme68x/bme68x"

2023-01-31 20:17 UTC, limerickcabin requested changes
line 48 should be #include "bme68x/bme68x.h"

2023-02-01 02:26 UTC, per1234 commented
Thanks @limerickcabin! Fixed by https://github.com/boschsensortec/BSEC-Arduino-library/compare/457f5fd54cebc9c6fd527c1d0613062e6ea56db6..eab0b8718d64c8b744f8d0dca593f860183056b0

2023-02-01 16:57 UTC, limerickcabin approved these changes

2023-02-01 16:58 UTC, limerickcabin commented
I also would like Bosch to restore the config folder

2023-02-01 18:46 UTC, per1234 commented
I also encountered errors related to the configuration when I ran some of the library's examples. I am not familiar with this project (I have only used it as a transitory dependency via the "[Arduino_MKRIoTCarrier](https://github.com/arduino-libraries/Arduino_MKRIoTCarrier)" library) so I wasn't sure whether the error was because I hadn't done some setup that is the user's responsibility.

I would suggest that work related to the configuration folder be considered a separate task from the more straightforward fix I propose here.

2023-02-02 02:48 UTC, mjechow commented
Awful realease. This is not the only problem. config/ directory is missing (not even the examples are working). Furthermore member names (status -> bsecStatus) and definitions (BME680_OK -> BME68X_OK) changed and that's not documented in the changelog, neither marked as an non backwards compatible release.

2023-02-04 13:29 UTC, Toner71 commented
> 

Did you managed to correct the compile errors related to the names^

2023-02-04 14:00 UTC, mjechow commented
Me? Yes. I can compile my project and run it smoothly.

2023-02-04 16:10 UTC, noanight commented
compilation works now by fixing the path to the includes mentionend above and....trying the basic example by adding #define LED_BUILTIN 39 but the linkage fails with: 
```shell
Arduino: 1.8.19 (Linux), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

Library BSEC_Software_Library has been declared precompiled:
Using precompiled library in /media/daten/projekte/esp32/aztouch/arduino-1.8.19/portable/sketchbook/libraries/BSEC_Software_Library/src/esp32
libraries/BSEC_Software_Library/BSEC_Software_Library.a(bsec.cpp.o):(.literal._ZN4Bsec18updateSubscriptionEP21bsec_virtual_sensor_thf+0x0): undefined reference to `bsec_update_subscription'
libraries/BSEC_Software_Library/BSEC_Software_Library.a(bsec.cpp.o):(.literal._ZN4Bsec15readProcessDataEx19bsec_bme_settings_t+0x8): undefined reference to `bsec_do_steps'
libraries/BSEC_Software_Library/BSEC_Software_Library.a(bsec.cpp.o):(.literal._ZN4Bsec11beginCommonEv+0x0): undefined reference to `bsec_init'
libraries/BSEC_Software_Library/BSEC_Software_Library.a(bsec.cpp.o):(.literal._ZN4Bsec11beginCommonEv+0x4): undefined reference to `bsec_get_version'
libraries/BSEC_Software_Library/BSEC_Software_Library.a(bsec.cpp.o):(.literal._ZN4Bsec3runEv+0x0): undefined reference to `bsec_sensor_control'
libraries/BSEC_Software_Library/BSEC_Software_Library.a(bsec.cpp.o): In function `Bsec::updateSubscription(bsec_virtual_sensor_t*, unsigned char, float)':
/media/daten/projekte/esp32/aztouch/arduino-1.8.19/portable/sketchbook/libraries/BSEC_Software_Library/src/bsec.cpp:574: undefined reference to `bsec_update_subscription'
libraries/BSEC_Software_Library/BSEC_Software_Library.a(bsec.cpp.o): In function `Bsec::readProcessData(long long, bsec_bme_settings_t)':
/media/daten/projekte/esp32/aztouch/arduino-1.8.19/portable/sketchbook/libraries/BSEC_Software_Library/src/bsec.cpp:574: undefined reference to `bsec_do_steps'
libraries/BSEC_Software_Library/BSEC_Software_Library.a(bsec.cpp.o): In function `Bsec::beginCommon()':
/media/daten/projekte/esp32/aztouch/arduino-1.8.19/portable/sketchbook/libraries/BSEC_Software_Library/src/bsec.cpp:574: undefined reference to `bsec_init'
/media/daten/projekte/esp32/aztouch/arduino-1.8.19/portable/sketchbook/libraries/BSEC_Software_Library/src/bsec.cpp:574: undefined reference to `bsec_get_version'
libraries/BSEC_Software_Library/BSEC_Software_Library.a(bsec.cpp.o): In function `Bsec::run()':
/media/daten/projekte/esp32/aztouch/arduino-1.8.19/portable/sketchbook/libraries/BSEC_Software_Library/src/bsec.cpp:574: undefined reference to `bsec_sensor_control'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board ESP32 Dev Module.


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
``

2023-02-05 14:34 UTC, Toner71 commented
The examples for Mkr Iot REV2 along with a MKR WiFi 1010 now compile perfectly on the Web Editor but still got tons of errors on the 2.0,1 IDE...

2023-02-05 15:09 UTC, per1234 commented
Hi @Toner71. Please post about the problem on the Arduino Forum. I'm sure we'll be able to help you out over there:

https://forum.arduino.cc/

2023-02-21 19:14 UTC, stony2k commented
Are there any new when the config files will ne added? Without them the new release is only half usefull near to unusefull.

2023-02-23 16:15 UTC, vvs551 commented
> 

The same problem!

2023-02-23 17:06 UTC, pjmi1 commented
It's frustrating, isn't it?
However, I have just had success moving over to the newer BSEC2 library. Its implementation for Arduino is similar to BSEC1 apart from the loop() has callbacks for each metric and handles its timing requirements internally so must be called continuously (I think). There are 2 config files currently and even on the BME680 can give a probability of detecting hand sanitiser, alcohol, which actually works!
https://github.com/boschsensortec/Bosch-BSEC2-Library 
+ also needs https://github.com/BoschSensortec/Bosch-BME68x-Library

2023-02-24 12:14 UTC, mjechow commented
> It's frustrating, isn't it? However, I have just had success moving over to the newer BSEC2 library. Its implementation for Arduino is similar to BSEC1 apart from the loop() has callbacks for each metric and handles its timing requirements internally so must be called continuously (I think). There are 2 config files currently and even on the BME680 can give a probability of detecting hand sanitiser, alcohol, which actually works! https://github.com/boschsensortec/Bosch-BSEC2-Library
> 
>     * also needs https://github.com/BoschSensortec/Bosch-BME68x-Library

I was trying to do the exact same thing. Thanks for the tip with the second lib. I should have read the readme. ;-)
Seems to work so far!

2023-03-02 08:58 UTC, eclipse1985 commented
Hey there, thank you so much for fixing this 🙏 ! @limerickcabin  there's any cache to see this merged soon? At the moment, all users of Arduino Cloud (which uses the latest version of the library as default) are suffering from this issue

2023-03-14 20:50 UTC, per1234 commented
Closing as duplicated by https://github.com/boschsensortec/BSEC-Arduino-library/commit/95422f742a279e57b16026839ef445af6f89d47a

2023-03-14 20:50 UTC, closed without merging